events {
    # Maximum number of simultaneous connections
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 777 ssl;
        server_name rshaheen.42.fr;

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        # Root directory containing WordPress files
        root /var/www/html;
        # Default files to look for when accessing a directory
        index index.php index.html;

        location / {
            # Try to serve a real file or directory first.
            # If not found, send the request to WordPress index.php
            # so WordPress can handle routing.
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            # Forward PHP requests to the WordPress container
            fastcgi_pass wordpress:9001;
            # Default PHP script to execute
            fastcgi_index index.php;
            # Load standard FastCGI parameters
            include fastcgi_params;
            # Pass the original host header to PHP-FPM
            fastcgi_param HTTP_HOST $http_host;
             # Tell PHP-FPM which PHP file should be executed
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
